# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

permissions:
  contents: read

env:
  FORCE_COLOR: 2

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - { v: 22 }
          - { v: 24, isLatest: yes }

    steps:
    - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
    - name: Use Node.js ${{ matrix.node-version.v }}
      uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
      with:
        node-version: ${{ matrix.node-version.v }}
    - run: npm clean-install
    - run: npm audit signatures
    - run: npm run all
    - run: npm run test

    - name: '[PR Preview] Upload dist folder'
      if: ${{github.event_name == 'pull_request' && matrix.node-version.isLatest}}
      uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
      with:
        name: dist
        path: |
          dist

    - name: '[PR Preview] Store PR metadata'
      if: ${{github.event_name == 'pull_request' && matrix.node-version.isLatest}}
      run: |
        touch ./pr_metadata.ini
        echo "pr=${{github.event.number}}" >> ./pr_metadata.ini
        echo "ref=${{github.sha}}" >> ./pr_metadata.ini

    - name: '[PR Preview] Upload PR metadata'
      if: ${{github.event_name == 'pull_request' && matrix.node-version.isLatest}}
      uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
      with:
        name: pr_metadata
        path: ./pr_metadata.ini
