name: Deploy PR Preview

on:
  workflow_run:
    workflows: [build]
    types:
      - completed

permissions:
  contents: read
  actions: write
  deployments: write

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    environment: workflows
    if: ${{github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success'}}
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: '24'
      - run: npm clean-install

      - name: Download all artifacts (dist folder and pr_metadata)
        uses: dawidd6/action-download-artifact@ac66b43f0e6a346234dd65d4d0c8fbb31cb316e5 # v11
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          run_id: ${{github.event.workflow_run.id}}
          allow_forks: true

      - name: Read pr_metadata
        id: pr_metadata
        run: cat pr_metadata/pr_metadata.ini >> $GITHUB_OUTPUT

      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{secrets.NETLIFY_AUTH_TOKEN}}
          NETLIFY_SITE_ID: ${{secrets.NETLIFY_SITE_ID}}
        run: ./node_modules/.bin/netlify deploy --no-build --dir=. --alias=pr-${{steps.pr_metadata.outputs.pr}}

      - name: Run afterDeploy script
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          script: |
            const { afterDeploy } = await import('${{github.workspace}}/scripts/pr_preview.js');
            await afterDeploy({ core, github, context })(
              '${{steps.pr_metadata.outputs.pr}}',
              '${{steps.pr_metadata.outputs.ref}}',
            );
